#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL="https://download.dokuwiki.org/src/dokuwiki/dokuwiki-rc.tgz"

dl $URL /usr/local/src
