#!/bin/sh -ex

ADMIN_USER=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/dokuwiki

WIKINAME="TurnkeyLinux+DokuWiki"

# unpack
tar -zxf $SRC/dokuwiki-rc.tgz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/dokuwiki-* $WEBROOT
chown -R root:root $WEBROOT

chown www-data:www-data /var/www/dokuwiki/lib
chown -R www-data:www-data /var/www/dokuwiki/data
chown -R www-data:www-data /var/www/dokuwiki/conf

# apache configuration
a2dissite 000-default
a2ensite dokuwiki
a2enmod rewrite

# start apache
service apache2 start

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL
$CURL $URL --data "l=en&d%5Btitle%5D=${WIKINAME}&d%5Bacl%5D=on&d%5Bsuperuser%5D=${ADMIN_USER}&d%5Bfullname%5D=${ADMIN_USER}&d%5Bemail%5D=${EMAIL}&d%5Bpassword%5D=turnkey&d%5Bconfirm%5D=turnkey&d%5Bpolicy%5D=1&d%5Blicense%5D=cc-by-sa&d%5Bpop%5D=on&submit="

service apache2 stop

# set dokuwiki permissions (anonymous: create, authenticated: upload)
cat > $WEBROOT/conf/acl.auth.php<<EOF
*                     @ALL        4
*                     @user       8
EOF

# welcome page
STARTPAGE=$WEBROOT/data/pages/start.txt
cat >$STARTPAGE<<EOF
====== Getting started ======

  * Log in as **admin** and start your wiki!
  * Refer to the [[https://www.turnkeylinux.org/dokuwiki|TurnKey DokuWiki release notes]]
  * [[wiki:syntax|Wiki Syntax]]
  * [[wiki:dokuwiki|Local DokuWiki documentation]]
  * [[doku>manual|The official DokuWiki manual]]
EOF

rm $WEBROOT/install.php

cd $WEBROOT/lib/plugins
git clone https://github.com/splitbrain/dokuwiki-plugin-upgrade upgrade

# don't remove previous chown commands, they break the curl install
chown -R www-data:www-data /var/www/dokuwiki
